[package]
name = "jhp_executor"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
v8 = { workspace = true }
jhp_parser = { path = "../parser" }
